#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

[DEFAULT]
pre = setup
quiet = False
pre_user = root
user = root
timeout = 600
post_user = root
post = cleanup
failsafe_user = root
failsafe = callbacks/zfs_failsafe
outputdir = /var/tmp/test_results
tags = ['functional']

[tests/functional/cli_root/zpool_create]
tests = ['zpool_create_001_pos', 'zpool_create_007_neg',
    'zpool_create_009_neg', 'zpool_create_011_neg',
    'zpool_create_012_neg',
    'zpool_create_017_neg','zpool_create_019_pos',
    'zpool_create_021_pos', 'zpool_create_022_pos',
    'zpool_create_023_neg',
    'zpool_create_encrypted', 'zpool_create_crypt_combos',
    'zpool_create_features_001_pos',
    'zpool_create_features_004_neg',
    'zpool_create_features_005_pos']
tags = ['functional', 'cli_root', 'zpool_create']

[tests/functional/zvol/zvol_cli]
tests = ['zvol_cli_001_pos', 'zvol_cli_002_pos', 'zvol_cli_003_neg']
tags = ['functional', 'zvol', 'zvol_cli']

[tests/functional/zvol/zvol_misc]
tests = ['zvol_misc_002_pos', 'zvol_misc_zil']
tags = ['functional', 'zvol', 'zvol_misc']

[tests/functional/io]
tests = ['sync', 'psync', 'posixaio', 'mmap']
tags = ['functional', 'io']

[tests/functional/cli_root/zfs]
tests = ['zfs_001_neg']
tags = ['functional', 'cli_root', 'zfs']

[tests/functional/cli_root/zdb]
tests = ['zdb_002_pos', 'zdb_003_pos',
    'zdb_args_neg', 'zdb_args_pos']

[tests/functional/cli_root/zfs_create]
tests = ['zfs_create_001_pos', 'zfs_create_002_pos', 'zfs_create_003_pos',
    'zfs_create_004_pos', 'zfs_create_005_pos', 'zfs_create_006_pos',
    'zfs_create_007_pos', 'zfs_create_008_neg', 'zfs_create_009_neg',
    'zfs_create_010_neg', 'zfs_create_011_pos', 'zfs_create_012_pos',
    'zfs_create_013_pos', 'zfs_create_encrypted',
    'zfs_create_crypt_combos', 'zfs_create_dryrun', 'zfs_create_verbose']
tags = ['functional', 'cli_root', 'zfs_create']

[tests/functional/cli_root/zfs_create]
tests = ['zfs_create_001_pos', 'zfs_create_002_pos', 'zfs_create_003_pos',
    'zfs_create_004_pos', 'zfs_create_005_pos', 'zfs_create_006_pos',
    'zfs_create_007_pos', 'zfs_create_008_neg', 'zfs_create_009_neg',
    'zfs_create_010_neg', 'zfs_create_011_pos', 'zfs_create_012_pos',
    'zfs_create_013_pos', 'zfs_create_encrypted', 'zfs_create_crypt_combos']
tags = ['functional', 'cli_root', 'zfs_create']

[tests/functional/cli_user/zpool_list]
tests = ['zpool_list_001_pos', 'zpool_list_002_neg']
user =
tags = ['functional', 'cli_user', 'zpool_list']

[tests/functional/cli_user/zfs_list]
tests = ['zfs_list_001_pos', 'zfs_list_002_pos', 'zfs_list_003_pos',
    'zfs_list_004_neg', 'zfs_list_008_neg']
user =
tags = ['functional', 'cli_user', 'zfs_list']

[tests/functional/cli_root/zpool_set]
tests = ['zpool_set_001_pos', 'zpool_set_002_neg', 'zpool_set_003_neg']
tags = ['functional', 'cli_root', 'zpool_set']

[tests/functional/cli_root/zpool_get]
tests = ['zpool_get_001_pos', 'zpool_get_002_pos', 'zpool_get_003_pos',
    'zpool_get_004_neg', 'zpool_get_005_pos']
tags = ['functional', 'cli_root', 'zpool_get']

[tests/functional/cli_root/zfs_set]
tests = ['cache_001_pos', 'cache_002_neg',
    'checksum_001_pos', 'compression_001_pos']
tags = ['functional', 'cli_root', 'zfs_set']

[tests/functional/cli_root/zfs_get]
tests = ['zfs_get_001_pos', 'zfs_get_002_pos',
    'zfs_get_005_neg', 'zfs_get_006_neg', 'zfs_get_007_neg',
    'zfs_get_008_pos', 'zfs_get_010_neg']
tags = ['functional', 'cli_root', 'zfs_get']
