
[DEFAULT]
pre = setup
quiet = False
pre_user = root
user = root
timeout = 600
post_user = root
post = cleanup
failsafe_user = root
failsafe = callbacks/zfs_failsafe
outputdir = /var/tmp/test_results
tags = ['functional']

[tests/functional/raidz]
tests = ['raidz_001_neg', 'raidz_002_pos', 'raidz_003_pos', 'raidz_004_pos']
tags = ['functional', 'raidz']

[tests/functional/removal]
pre =
tests = ['removal_with_add', 'remove_raidz']
tags = ['functional', 'removal']

[tests/functional/refreserv]
tests = ['refreserv_multi_raidz']
tags = ['functional', 'refreserv']

[tests/functional/replacement]
pre =
post=
tests = ['rebuild_raidz']
tags = ['functional', 'replacement']

[tests/functional/cli_root/zpool_add]
pre =
post=
tests = ['zpool_add_001_pos','zpool_add_010_pos']
tags = ['functional', 'cli_root', 'zpool_add']

[tests/functional/slog]
pre =
tests = ['slog_001_pos', 'slog_002_pos', 'slog_003_pos', 'slog_004_pos',
    'slog_005_pos', 'slog_006_pos','slog_008_neg',
    'slog_009_neg', 'slog_011_neg']
tags = ['functional', 'slog']

[tests/functional/cli_root/zpool_remove]
pre =
post=
tests = ['zpool_remove_001_neg']
tags = ['functional', 'cli_root', 'zpool_remove']

[tests/functional/pool_names]
tests = ['pool_names_002_neg']
pre =
post =
tags = ['functional', 'pool_names']

[tests/functional/cache]
pre =
post=
tests = ['cache_001_pos', 'cache_002_pos', 'cache_003_pos', 'cache_004_neg',
    'cache_005_neg','cache_007_neg', 'cache_008_neg',
    'cache_009_pos', 'cache_011_pos']
tags = ['functional', 'cache']

[tests/functional/online_offline]
tests = ['online_offline_002_neg']
tags = ['functional', 'online_offline']
